config/routes.rb
Rails.application.routes.draw do
  get "users/new"
  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  def help
  end
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = "")
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= t ".the" %> <a href="http://www.railstutorial.org/"> <%= t ".rubyrails" %></a>
    <%= t ".by" %> <a href="http://www.michaelhartl.com/"><%= t ".michael" %></a>
  </small>
  <nav>
    <ul>
      <li><%= link_to t(".about"), about_path %></li>
      <li><%= link_to t(".contact"), contact_path %></li>
      <li><%= link_to t(".new"), "#" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t(".logo"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t(".home"), root_path %></li>
        <li><%= link_to t(".help"), help_path %></li>
        <li><%= link_to t(".login"), "#" %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
    <%= yield %>
    <%= render "layouts/footer" %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide :title, t(".about")  %>
<h1><%= t ".about" %></h1>
<p>
  <%= t ".the" %> <a href="http://www.railstutorial.org/"><em>
  <%= t ".rubyrails"%></em></a> <%= t ".is" %>
  <a href="http://www.railstutorial.org/book"><%= t ".book" %></a> <%= t ".and" %>
  <a href="http://screencasts.railstutorial.org/"><%= t ".screen" %></a> <%= t ".teach" %>
  <a href="http://rubyonrails.org/"><%= t ".ruby" %></a>
  <%= t ".thisis" %>
</p>

app/views/static_pages/contact.html.erb
<% provide :title, t(".contact") %>
<h1><%= t ".contact" %></h1>
<p><%= t ".contactruby" %>
  <a href="http://www.railstutorial.org/contact"><%= t ".contactpage" %></a>.
</p>

app/views/static_pages/help.html.erb
<% provide :title, t(".help") %>
<h1><%= t ".help" %></h1>
<p>
  <%= t ".gethelp" %>
  <a href="http://www.railstutorial.org/help"><%= t ".railshelp" %></a>.
  <%= t ".tohelp" %>
  <a href="http://www.railstutorial.org/book"><em><%= t ".ruby" %></em>
  <%= t ".book" %></a>.
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1><%= t ".welcome" %></h1>
  <h2>
    <%= t ".homepage" %>
    <a href="http://www.railstutorial.org/"><%= t ".ruby" %></a>
    <%= t ".sample" %>
  </h2>
  <%= link_to t(".signup"), signup_path, class: "btn btn-lg btn-primary" %>
</div>
<%= link_to image_tag("rails.png", alt: t(".raillogo")), "http://rubyonrails.org/" %>

app/views/users/new.html.erb
<% provide :title, t(".sign") %>